WildMeOrg/Wildbook

src/main/resources/bundles/es/submit.properties
Corrected some Spanish mistakes/literal translations from English. Could still be improved.
=> Corrected some Spanish mistakes

src/main/resources/bundles/es/encounters.properties
Change translation of 'language' from 'lengua' to 'idioma'
=> Spanish edit

src/main/resources/bundles/en/index.properties, src/main/resources/bundles/es/index.properties, src/main/resources/emails/en/email-template.html, src/main/resources/emails/en/encounterDataUpdate.html, src/main/resources/emails/en/individualAddEncounter.html, src/main/resources/emails/en/individualCreate.html, src/main/resources/emails/en/individualDataUpdate.html, src/main/resources/emails/en/individualUpdate.html, src/main/resources/emails/en/newSubmission.html, src/main/resources/emails/en/passwordReset.html
Some little changes and the email's Spanish translations (only the html files)
=> email's Spanish translations

src/main/webapp/footer.jsp, src/main/webapp/header.jsp
Tracker for miscellaneous/uncategorized web surfing. When merging master into your branch, accept the tracker specific to your site, NOT this tracker
=> Misc GA tracker

src/main/webapp/individuals.jsp, src/main/webapp/javascript/bubbleDiagram/coOccurrenceGraph.js, src/main/webapp/javascript/relationshipDiagrams/forceLayoutAbstract.js, src/main/webapp/javascript/relationshipDiagrams/jsonParser.js
All explicit occurrences are now guaranteed to be included in the CoOccurrence graph, provided the specified maxNumNodes quantity allows
CoOccurrence graph spatial/temporal filters initialize (and reset) to 0
=> CoOccurrence Graph Feature Follow-up

.dockerfiles/config/commonConfiguration.properties, .dockerfiles/config/context.xml, .dockerfiles/config/jdoconfig.properties, .dockerfiles/config/server.xml, Dockerfile, scripts/build.docker.sh, src/main/webapp/edm/init.jsp
This comes from
https://github.com/WildMeOrg/dev/tree/master/devops/wildbook/edm
with minor location modifications, because it now resides alongside
the code.
=> Add container definition

.github/workflows/docker-publish.yml, scripts/build.docker.sh
Builds the `wildme/edm:latest` image on push to `next-gen` branch
=> Action build image

src/main/java/org/ecocean/ia/IA.java, src/main/webapp/encounters/encounter.jsp
Main commit is cherry picked and slightly modified from a different branch.
I also noticed today that I accidentally pushed something to master that is not ready for master yet, so a commit here will silence that change as well.
=> Missing acmid fix

src/main/java/org/ecocean/JsonProperties.java, src/main/java/org/ecocean/ia/IA.java, src/main/java/org/ecocean/servlet/importer/StandardImport.java, src/main/java/org/ecocean/servlet/importer/UpdateStandard.java, src/main/java/org/ecocean/servlet/importer/WebImport.java, src/main/webapp/encounters/encounter.jsp, src/main/webapp/import/uploadFooter.jsp, src/main/webapp/individualSearch.jsp, src/main/webapp/individuals.jsp, src/main/webapp/javascript/localUploader.js, src/main/webapp/javascript/uploader.js, src/main/webapp/match.jsp, src/main/webapp/merge.jsp
Note that this incorporates some of today's changes from WB-1497, so some of that code will look eerily familiar.
=> Kosher media asset filenames

src/main/java/org/ecocean/CommonConfiguration.java, src/main/java/org/ecocean/Encounter.java, src/main/java/org/ecocean/LocationID.java, src/main/resources/bundles/commonConfiguration.properties, src/main/resources/bundles/en/encounter.properties, src/main/resources/bundles/es/encounter.properties, src/main/resources/bundles/fr/encounter.properties, src/main/webapp/encounters/encounter.jsp, src/main/webapp/iaResults.jsp
Same thing as https://github.com/WildMeOrg/Wildbook/pull/106, only stripped of anything LOCAL for giraffe.
=> cherry pick changes from locationId-update

src/main/java/org/ecocean/Annotation.java, src/main/java/org/ecocean/ia/Task.java, src/main/java/org/ecocean/media/MediaAsset.java, src/main/webapp/encounters/encounterMediaGallery.jsp
Basically a bunch of `.equals()` and `.hashCode()` that we need to be able to do List `compare()` on objects; then a way to traverse a Task tree to see if it contains a specified object (`task.deepContains(obj)`).
This allows us to choose more wisely the list of Tasks which are used in encounterMediaGallery.jsp
=> WB-1691: hamburger task bug

src/main/java/org/ecocean/MetricsBot.java, src/main/java/org/ecocean/metrics/Prometheus.java, src/main/webapp/iaResults.jsp
These lines are taking up a lot of the logs and I'd like to mute them for now.
=> silencio por favor

src/main/resources/bundles/commonConfiguration.properties, src/main/webapp/pictureBook.jsp
Add keywords to commonConfiguration.properties for photos to be included in the individualSearchResults export of a photobook.
=> WB-384 make photoBookKeywords customizable

src/main/java/org/ecocean/Shepherd.java
Alpha sorting projects list looks much cleaner.
=> WB-1914: alpha sort projects list

src/main/webapp/import.jsp
Workaround for differing hierarchies of tasks depending on how jobs were initiated and the number of algorithms involved.
=> WB-1911: ugly workaround for different hierarchies

src/main/java/org/ecocean/servlet/importer/StandardImport.java
Alright, major changes to remove global variables but seeing so much smoother, simultaneous bulk upload behavior.
=> Fix bulk import multi user

src/main/webapp/imports.jsp
Fix query for number of Media Assets per bulk import
=> WB-1928: fix listed num media assets

src/main/java/org/ecocean/servlet/GetCurrentIAInfo.java, src/main/webapp/WEB-INF/web.xml, src/main/webapp/iaResults.jsp, src/main/webapp/iaResultsAnnotFeed.jsp, src/main/webapp/iaResultsNoMatch.jsp, src/main/webapp/iaResultsSetID.jsp
Fixes link to annotation match on the project page list of Encounter. Fix improves the link especially for two conditions:
- bulk imported data where the root task is not the Task we want to link to
- multi-algorithm matching where one or more algorithms may be linked under a root Task, which may not be the bulk import root task either
=> WB-1941: better link to latest match result for an annotation

src/main/java/org/ecocean/Project.java, src/main/resources/bundles/en/project.properties, src/main/resources/bundles/es/project.properties, src/main/resources/bundles/fr/project.properties, src/main/webapp/cust/mantamatcher/styles/_wildbook.less, src/main/webapp/javascript/sort-table.js, src/main/webapp/projects/project.jsp
Make existing Projects table sortable by clicking on the column header. Add occurrence/sighting column.
=> WB-1948: sortable projects table

src/main/java/org/ecocean/MetricsBot.java, src/main/java/org/ecocean/servlet/EncounterVMData.java, src/main/webapp/encounters/encounterVM.jsp
Massive speed improvements to visual matcher plus better Shepherd handling in the metrics collector
=> Wb 1965 vm timeout

src/main/java/org/ecocean/RestClient.java, src/main/java/org/ecocean/cache/CachedQuery.java, src/main/java/org/ecocean/ia/WbiaQueueUtil.java, src/main/java/org/ecocean/identity/IdentityServiceLog.java, src/main/webapp/appadmin/wbiaQueueTest.jsp, src/main/webapp/encounters/encounter.jsp, src/main/webapp/iaLogs.jsp, src/main/webapp/iaResults.jsp, src/main/webapp/import.jsp
Wb 1943: Better report WBIA queue size in Wildbook to warn users of traffic ahead of them.
=> Wb 1943: Better report WBIA queue size in Wildbook

src/main/java/org/ecocean/Shepherd.java
WB-1971: clone only into the immediate Encounter's projects
=> WB-1971: clone only into the immediate Encounter's projects

src/main/webapp/encounters/encounter.jsp, src/main/webapp/occurrence.jsp, src/main/webapp/occurrenceMapEmbed.jsp
Tigther up GPS display in silos security conditions
=> Tighten gps display security

src/main/java/org/ecocean/JsonProperties.java, src/main/java/org/ecocean/MetricsBot.java, src/main/webapp/appadmin/wildbookIAQueueStats.jsp
Improve tracking of completed ID jobs
=> Callback tweaks

pom.xml, src/main/java/org/ecocean/User.java, src/main/java/org/ecocean/security/Collaboration.java, src/main/java/org/ecocean/security/HiddenDataReporter.java, src/main/java/org/ecocean/security/HiddenIndividualReporter.java, src/main/java/org/ecocean/servlet/ServletUtilities.java, src/main/java/org/ecocean/servlet/export/GetIndividualSearchGoogleMapsPoints.java, src/main/webapp/WEB-INF/web.xml, src/main/webapp/appadmin/duplicateAnnotations.jsp, src/main/webapp/appadmin/sharedAnnotations.jsp, src/main/webapp/encounters/encounter.jsp, src/main/webapp/encounters/encounterCR.jsp, src/main/webapp/encounters/encounterMediaGallery.jsp, src/main/webapp/encounters/projectManagement.jsp, src/main/webapp/encounters/spotMatchingAlgorithm.jsp, src/main/webapp/iaResultsNoMatch.jsp, src/main/webapp/iaResultsSetID.jsp, src/main/webapp/import.jsp, src/main/webapp/imports.jsp, src/main/webapp/occurrence.jsp
Add deeper security checks on bulk imports
=> Sec review

src/main/java/org/ecocean/MarkedIndividual.java, src/main/webapp/individuals.jsp
Part of some speed improvements for individuals.jsp
=> Faster individual images

src/main/java/org/ecocean/servlet/EncounterForm.java
set submitterID = public if we can'r figure it out on a manual submission
=> set submitterID = public

src/main/webapp/WEB-INF/web.xml
open encounter page for public submissions
=> open encounter page for public submissions

src/main/java/org/ecocean/acm/AcmUtil.java, src/main/java/org/ecocean/ia/plugin/WildbookIAM.java
Supports acm ID resynch with a fresh WBIA
=> Persist these annot acmID changes

src/main/java/org/ecocean/servlet/importer/StandardImport.java
allows `withName()` lookup to fix #285
=> fixes duplicate individuals made during imports

src/main/java/org/ecocean/MetricsBot.java
Example: Giraffa tippelskirchi thornicrofti
=> Fix subspecies metrics

src/main/java/org/ecocean/CommonConfiguration.java, src/main/resources/bundles/googleKeys.properties, src/main/webapp/header.jsp
added google script manager 
googlekeys.properties a new variable is added gtm_key its value should be replaced before deployment
=> added google tag manager to header

README.md
old text was not in markdown format; adjusted syntax. fixed support references and language changes for wildbook and wild me
=> clean up old text add pr workflow

src/main/java/org/ecocean/Keyword.java, src/main/java/org/ecocean/Shepherd.java
Resolves [https://github.com/WildMeOrg/Wildbook/issues/261](url)
=> Keywords sorted for alphabetical ordering on encounter page

src/main/java/org/ecocean/servlet/importer/StandardImport.java
Resolves https://github.com/WildMeOrg/Wildbook/issues/284
Encounter.state preprocessed to set it to lowercase during bulk import.
=> Encounter state lowercase during bulk import

devops/wildbook/_config/iot/commonConfiguration.properties, devops/wildbook/_config/master/commonConfiguration.properties, src/main/java/org/ecocean/CommonConfiguration.java, src/main/java/org/ecocean/NotificationMailer.java, src/main/java/org/ecocean/servlet/EncounterForm.java, src/main/java/org/ecocean/servlet/IndividualAddEncounter.java, src/main/resources/bundles/commonConfiguration.properties, src/main/resources/emails/en/individualAddEncounter.html, src/main/resources/emails/en/individualCreate.html, src/main/resources/emails/en/individualUpdate.html, src/main/resources/emails/en/newSubmission.html
Resolves https://github.com/WildMeOrg/Wildbook/issues/290
The 'Do not reply to this email' message has been added to the bottom of the new encounter submission emails.
=> Do not reply message added to new encounter submission emails

src/main/java/org/ecocean/Annotation.java, src/main/java/org/ecocean/servlet/export/EncounterAnnotationExportExcelFile.java, src/main/webapp/WEB-INF/web.xml, src/main/webapp/encounters/exportSearchResults.jsp
added new export option (Encounter Annotation) in Encounter search 
**Changes**
- added EncounterAnnotationExportExcelFile class 
- added method getBboxAsString in Annoation.java
- updated web.xml for new url EncounterAnnotationExportExcelFile
=> added encounter anntation export

src/main/java/org/ecocean/security/Collaboration.java
No change to behavior. Solves a database connection handling issue and an order of relationship checking iss beyween two users in the Collaboration check.
=> Fix order and db handling for orgAdmin automatic collabs

src/main/java/org/ecocean/security/Collaboration.java
[Plain-text summary description of the solution]
=> Final debug of collabs

src/main/java/org/ecocean/servlet/export/EncounterAnnotationExportExcelFile.java
Added Encounter.photographer0.fullName column into Encounter Annotation Export
=> added photographer name

src/main/java/org/ecocean/CommonConfiguration.java, src/main/java/org/ecocean/servlet/SessionExtend.java, src/main/resources/bundles/commonConfiguration.properties, src/main/resources/bundles/en/header.properties, src/main/resources/bundles/es/header.properties, src/main/resources/bundles/fr/header.properties, src/main/resources/bundles/it/header.properties, src/main/webapp/WEB-INF/web.xml, src/main/webapp/header.jsp
currently there is default 30 mintues of timeout if user is not active to handle this situation  a popup is added  which shows up after 20 mintues of inactivity and allow user to extend session 
**Changes**
- added endpoint SessionExtend to extend the current session
- added modal in header.jsp 
- added sessionWarningTime variable commonConfiguration
=> added a warning popup for login user who is inactive for 20 minutes

src/main/java/org/ecocean/EncounterQueryProcessor.java, src/main/webapp/encounters/encounterSearch.jsp
Added Occurrence ID filter under metadata filters to allow filter encounter based on Occurrence ID
**Changes**
- added input field in encounterSearch.jsp
- added occurrenceID filter in EncounterQueryProcessor.java
=> added Occurrence id filter in Encounter Search

src/main/java/org/ecocean/EncounterQueryProcessor.java, src/main/webapp/encounters/encounterSearch.jsp
Added Social Filters (social unit and social role) on Encounter Search 
social unit filter works as follow
1. get the social units and associated individualIDs from the social units
2. use these individualIDs to filter the Encounters
social role filter works as fllow
1. fetch all the MarkedIndividuals
2. for each MarkedIndividuals gets all roles
3. if requested role is not present remove in MarkedIndividuals 
4. use these individualIDs to filter the Encounters
**Changes**
- added social filters dropdown in SearchResults.jsp
- added filters in EncounterQueryProcessor.java
=> Added social filter for Encounter Search

src/main/java/org/ecocean/CommonConfiguration.java, src/main/resources/bundles/commonConfiguration.properties, src/main/resources/bundles/en/header.properties, src/main/resources/bundles/es/header.properties, src/main/resources/bundles/fr/header.properties, src/main/resources/bundles/it/header.properties, src/main/webapp/header.jsp, src/main/webapp/welcome.jsp
added new text to popup warninig when countdown is over added a script to welcome.jsp (user login sucessfully) to close warning popup on other tabs
**Changes**
- added sessionCountdownTime in CommonConfiguration.properties
- added getSessionCountdownTime in CommonConfiguration.java 
- added a script in welcome.jsp which trigger popup close using local storage listener 
- added text to header.properties
=> added countdown to popup warning

src/main/webapp/import.jsp
alters id-initiation menu to:
- include all regions/locations
- allow multiselect
PR fixes #433
=> 433: bulk import id menu multiselect with all locations

src/main/java/org/ecocean/servlet/export/KinalyzerExport.java, src/main/webapp/individualSearchResultsExport.jsp
Kinalyzer is no longer accessible as a tool (it was a Univ. of Illinois-Chicago project), and at the request of Oregon State Univ. researchers, I have expanded the Kinalyzer CSV output to include more genetics information and to be more generally useful. This entails:
- Adding a header row
- Adding individual default name
- Adding individual haplotype
- Adding individual genetic sex
=> Convert Individual Search Kinalyzer export to more functional genetics export

src/main/java/org/ecocean/servlet/export/EncounterAnnotationExportExcelFile.java, src/main/java/org/ecocean/servlet/export/ExportColumn.java
updated Encounter Annotation Export add new column Encounter.sourceUrl and updated export extension to xlsx from xls
updated annotation logic
**Changes**
- added writeStringLabel in ExportColumn.java
- added Encounter.sourceUrl in export column
=> Carnivore multiple annotation

src/main/resources/bundles/en/individualSearchResultsExport.properties, src/main/resources/bundles/en/pictureBook.properties
update references to picture book to be consistent and generalized
PR fixes #413
**Changes**
- copy update and some comment cleanup
=> update english copy for picture book references

src/main/webapp/adoptananimal.jsp
copy was linguistically generalized but needs to be consistent with rest of copy page
PR fixes #258
**Changes**
- just copy changes
=> copy update

src/main/java/org/ecocean/security/HiddenDataReporter.java, src/main/java/org/ecocean/servlet/export/EncounterAnnotationExportExcelFile.java, src/main/java/org/ecocean/servlet/export/ExportColumn.java, src/main/java/org/ecocean/servlet/export/MultiValueExportColumn.java
updated export filename.
Updated the export file extension from .xls to .xlsx and integrated Apache POI via method overloading to support this change in the existing JVX-based flow.
**Changes**
- added writeHeaderLabel in ExportColumn.java which uses Apache POI
- added writeLabel in ExportColumn.java which uses Apache POI
- added writeLabel in MultiValueExportColumn.java which uses Apache POI
- added writeHiddenDataReport in HiddenDataReporter.java which uses Apache POI
=> updated Annotation Export file name and extension using Apache POI

frontend/src/components/AuthenticatedAppHeader.jsx, frontend/src/components/DiamondCard.jsx, frontend/src/components/header/AvatarAndUserProfile.jsx, frontend/src/components/home/Progress.jsx, frontend/src/locale/en.json, frontend/src/locale/es.json, frontend/src/locale/fr.json, frontend/src/locale/it.json
add some translations: encounters/annotations
=> I18n part2

frontend/src/components/Footer.jsx, frontend/src/constants/navMenu.js
temporarily hide ToU and pravicy policy entrance from header and footer
=> temporarily hide ToU and pravicy policy entrance from header and footer

frontend/src/components/UnAuthenticatedAppHeader.jsx, frontend/src/pages/Login.jsx
update username and password placeholders
adjust styles in header to make space for i18n text
=> update i18n and header style

src/main/webapp/iaResults.jsp, src/main/webapp/iaResultsSetID.jsp, src/main/webapp/merge.jsp
allow checking multiple boxes in matches to merge or assign across > 2 encounters
addresses #432
=> 432: multiselect match results

src/main/webapp/encounters/manualAnnotation.jsp
Used all viewpoints from `Annotation.java` for manual annotation, along with `----------` for annotation-less algorithms.
PR fixes #282
=> #282 All viewpoints made available in manual annotation

src/main/webapp/individuals.jsp
pass proper value for `individual` to fix bug
=> Pass proper value for individual to fix bug

src/main/webapp/individuals.jsp, src/main/webapp/javascript/bubbleDiagram/coOccurrenceGraph.js
The code for time/space sliders has been deleted as per the #278 requirements. 
PR fixes #278 
**Changes**
- Changes to UX:  As per #278 requirements, the time/space sliders don't show up anymore on the co-occurrence diagram. In addition, the spatial/temporal values are not shown on the graph. Instead, by default, the graph shows the count of the shared sightings between individuals.
- Callout: The code which updates the spatial/temporal values on the graph has been left commented out, since the logic in this file would anyhow be re-done during React development.
=> Simplified cooccurrence diagram

frontend/src/AuthenticatedSwitch.jsx, frontend/src/FrontDesk.jsx, frontend/src/UnAuthenticatedSwitch.jsx, frontend/src/components/AlertBanner.jsx, frontend/src/components/AuthenticatedAppHeader.jsx, frontend/src/components/UnAuthenticatedAppHeader.jsx, frontend/src/locale/en.json, frontend/src/locale/es.json, frontend/src/locale/fr.json, frontend/src/locale/it.json
add alert banner to provide context for the changes to let people know what is happening
=> add alert banner

src/main/webapp/encounters/encounter.jsp
- catch java exception to allow jsp to finish page js/html
- bonus catch of an ancient javascript function that was not closed correctly
=> bug where failing java (NPE) was causing encounter.jsp to end up incomplete

src/main/webapp/appadmin/iaBreakdownBySpecies.jsp
Ensures that subspecies (e.g., Giraffa tippelskirchi thornocrofti) are represented is the IA-related class and status breakdown for this data integrity page.
**Changes**
- Add subspecies support
=> Add subspecies support to analysis

frontend/src/constants/navMenu.js, frontend/src/locale/en.json, frontend/src/locale/es.json, frontend/src/locale/fr.json, frontend/src/locale/it.json
add bulk import logs back to react header
=> add bulk import logs back to react header

frontend/maven-build.sh
bugfix for bug found during testing
=> bugfix: building react needed different url value

src/main/resources/bundles/en/index.properties
=> fixed typo

frontend/src/GoogleTagManager.jsx
this value needs quotes to be passed to gtag function
=> add quotes to variable gaId

pom.xml
for each release, we need to update the wildbook version (until we get this automated into the build process)
No associated issue
**Changes**
- version update
=> manual update of wildbook version for 10.2.1 release

pom.xml
10.2.2 release with apis for external integration
=> version upgrade

src/main/webapp/contactus.jsp
Removed specific species references and references to non WM team for general
(PR does not fix a numbered issue)
=> species-neutral copy update

src/main/webapp/photographing.jsp
removed whale-specific references and added a references to the Wildbook help docs
(PR does not address specific issue number)
=> species-neutral copy for photo guidelines

devops/deploy/.dockerfiles/tomcat/commonConfiguration.properties, devops/development/.dockerfiles/tomcat/commonConfiguration.properties, src/main/resources/bundles/commonConfiguration.properties, src/main/resources/bundles/en/index.properties, src/main/webapp/citing.jsp, src/main/webapp/userAgreement.jsp
- add config option to prevent timeout bug
- more species neutral language
PR does not addressed numbered issue
=> Neutral config

src/main/java/org/ecocean/JsonProperties.java, src/main/java/org/ecocean/api/SiteSettings.java, src/main/webapp/appadmin/opensearchSync.jsp
squash a couple bugs and add some useful debugging for IA.json
=> Small fixes via seal testing

src/main/webapp/encounters/encounterSearch.jsp, src/main/webapp/individualSearch.jsp, src/main/webapp/occurrenceSearch.jsp
Fixes searching by subspecies in Encounter Search and Individual Search. Previously subspecies returned zero results. Now results are fully populated.
PR fixes #659
**Changes**
- Underscore swap and replace in encounterSearch.jsp
- Underscore swap and replace in individualSearch.jsp
=> Fix subsepcies search support

src/main/webapp/gallery.jsp
fix a gallery header background color issue caused by header updates
=> remove navBar class from gallery header

README.md, frontend/src/constants/footerMenu.js, frontend/src/constants/navMenu.js, src/main/resources/bundles/de/encounter.properties, src/main/resources/bundles/de/individuals.properties, src/main/resources/bundles/de/occurrence.properties, src/main/resources/bundles/en/encounter.properties, src/main/resources/bundles/en/individuals.properties, src/main/resources/bundles/en/occurrence.properties, src/main/resources/bundles/es/encounter.properties, src/main/resources/bundles/es/individuals.properties, src/main/resources/bundles/es/occurrence.properties, src/main/resources/bundles/fr/encounter.properties, src/main/resources/bundles/fr/individuals.properties, src/main/resources/bundles/fr/occurrence.properties, src/main/resources/bundles/it/encounter.properties, src/main/resources/bundles/it/individuals.properties, src/main/resources/bundles/it/occurrence.properties, src/main/resources/servletResponseTemplate.htm, src/main/webapp/footer.jsp
in support of doc site changeover, update docs references (including very outdated references). also adjusted donate link while in there to point directly to donate page rather than to redirect on website
PR fixes no named issue
=> point to new docs site and donate

src/main/webapp/overview.jsp
removed flukebook and ocean content from this page, neutralizing to center on Wildbook general messaging
PR does not fix a named issue
=> de-ocean'd the overview

pom.xml
update logback java dependency (via dependabot [PR 682](https://github.com/WildMeOrg/Wildbook/pull/682))
=> bump logback version

pom.xml
update org.json java libraries (based on dependabot [PR472](https://github.com/WildMeOrg/Wildbook/pull/472))
=> (way) upgrade org.json java library

src/main/java/org/ecocean/api/SearchApi.java, src/main/java/org/ecocean/api/SiteSettings.java, src/main/java/org/ecocean/api/UserHome.java, src/main/java/org/ecocean/api/UserInfo.java
hot-fix to encode api as utf-8
=> add utf-8 encoding to apis

src/main/java/org/ecocean/Encounter.java
- individualNickName
- individualFirstEncounterDate
- individualLastEncounterDate
=> add some additional fields to search api doc/results

frontend/src/components/Footer.jsx, src/main/java/org/ecocean/api/SiteSettings.java, src/main/webapp/footer.jsp
add version in both react and jsp footers.
version links to https://github.com/WildMeOrg/Wildbook/releases/tag/[versionnumber]
PR fixes #644
=> 644 add version in footer

src/main/resources/servletResponseTemplate.htm
the servletResponsiveTemplate.htm was missed when updating links of citation page
=> citation react

babel.config.js, eslint.config.mjs, frontend/src/components/Form/BioMeasurements.jsx, frontend/src/components/filterFields/LocationFilter.jsx, frontend/src/components/footer/FooterLink.jsx, frontend/src/components/svg/Logo.jsx, frontend/src/pages/EncounterSearch.jsx, package-lock.json, package.json
1. upgrade eslint and relative libraries to latest version
2. introduce more rules and more libraries to enforce stricter syntax and react hooks validation.
PR does not fix a numbered issue.
=> eslint upgrade

.github/workflows/nightly.yml, pom.xml
secret passed securely as parameter
Login the docker securely according to the news / incidents reported : https://it.slashdot.org/story/24/08/17/056242/github-actions-artifacts-leak-tokens-expose-cloud-services-and-repositories
**Changes**
- [bullet list include any model updates]
- [new or edited functions]
- [significant changes to UX]
- [design decisions, especially if architectural patterns are new/altered]
- [can use text, screenshots, or files]
- [a callout of any ##TODO or ##FIXMEs found/created as part of the fix]
=> Login docker securely 

src/main/java/org/ecocean/api/Projects.java, src/main/java/org/ecocean/api/UserHome.java, src/main/resources/bundles/en/projectList.properties, src/main/webapp/WEB-INF/web.xml, src/main/webapp/projects/projectList.jsp, tmp.js
Enabled system and specific user project access by  roles.
PR fixes #587
=> Enabled system and specific user project access by roles

src/main/webapp/index.jsp
should be the last changes for the snails release!
=> copy updates

.github/workflows/dev-maven-publish.yml
just redirecting branches with the branch name change
=> master to main

frontend/public/manifest.json, frontend/src/App.jsx, frontend/src/AuthenticatedSwitch.jsx, frontend/src/components/UnAuthenticatedAppHeader.jsx, frontend/src/components/filterFields/ApplyQueryFilter.jsx, frontend/src/components/header/AvatarAndUserProfile.jsx, frontend/src/components/home/LandingImage.jsx, frontend/src/components/home/LatestData.jsx, frontend/src/components/home/PickUpWhereYouLeft.jsx, frontend/src/components/home/Report.jsx, frontend/src/components/navBar/MultiLanguageDropdown.jsx, frontend/src/constants/navMenu.js, frontend/src/index.js, frontend/src/models/auth/useLogin.js, frontend/src/pages/EncounterSearch.jsx, frontend/src/pages/Login.jsx, frontend/src/pages/errorPages/ErrorPage.jsx
update hardcoded path "/react" to variable process.env.PUBLIC_URL
=> update react base path

src/main/java/org/ecocean/MetricsBot.java
Add three new metrics for researcher and cit sci Encounter metrics tracking
PR fixes #532 
**Changes**
- Add three new metrics for researcher and cit sci Encounter metrics tracking
=> Add three new metrics queries

frontend/src/pages/Login.jsx
don't check username and password until clicking at sign in button
=> remove sign in button constraint

src/main/webapp/iaResultsSetID.jsp
PR fixes #640 
- fixed / re-enabled email sending code when match is made
=> email notifications go out when individual matched via iaResults

pom.xml
10.4.0 release letsgo
PR does not fix numbered issue
=> manual version update

devops/README.md
minimum version declared for node
PR does not fix any numbered issue
=> formatting and version req

frontend/src/components/SpeciesSection.jsx, frontend/src/locale/en.json, frontend/src/pages/ReportEncounter.jsx
ISSUE: #797 
Added Species frame in Report Encounter page
PR fixes #797
=> [797] species frame

frontend/src/components/AdditionalCommentsSection.jsx, frontend/src/pages/ReportsAndManagamentPages/ReportEncounter.jsx, frontend/src/pages/ReportsAndManagamentPages/ReportEncounterStore.js
PR fixex: #796 
Added additional comments frame
=> [796] additional comments frame

frontend/src/locale/de.json, frontend/src/locale/en.json, frontend/src/locale/es.json, frontend/src/locale/fr.json, frontend/src/locale/it.json, frontend/src/pages/ReportsAndManagamentPages/DateTimeSection.jsx, frontend/src/pages/ReportsAndManagamentPages/ImageSection.jsx, frontend/src/pages/ReportsAndManagamentPages/ReportEncounter.jsx
1. Encounter Date is a required field and displays the asterisk (*)
2. If a user tries to submit with an empty Encounter Date field, it throws error
3. If user enters an invalid datetime, it throws error
4. Date and Time from EXIF populates with the date/time metadata extracted from the uploaded images
5. Selecting a Date and Time from EXIF populates the Encounter Date field with the selected information
PR fixes #794
=> 794 datetime frame

src/main/java/org/ecocean/servlet/export/EncounterSearchExportShapefile.java
Added individual name to shape export. maintained existing individual ID reference
PR fixes #852 
**Testing notes**
Confirmed that generated .dbf file had correct columns
Confirmed that full file package loaded
=> Shapefile includes individual name

src/main/java/org/ecocean/servlet/IndividualAddComment.java, src/main/webapp/individuals.jsp
Updated AddComment functionality for marked individuals. When a user adds a comment the comment board should automatically refresh and add the new comment without changing the page. 
PR fixes #576
**Changes**
- Modified individuals.jsp to do a post without taking the user away from the marked individual page and display the new comment, and the doPost function in IndividualAddComment.java to return the new comment after the database has been updated.
=> Updated AddComment Functionality

devops/deploy/.dockerfiles/tomcat/commonConfiguration.properties, src/main/java/org/ecocean/ImageProcessor.java, src/main/resources/bundles/commonConfiguration.properties, src/main/resources/emails/en/passwordReset.html, src/main/resources/servletResponseTemplate.htm, src/main/webapp/header.jsp
Found broken docs references while testing something else
PR does not address numbered issue
- docs references updated
- email references updated to wildme instead of wildbook
=> Docs and email link updates

frontend/src/components/FilterPanel.jsx, frontend/src/pages/EncounterSearch.jsx
update click and scroll behavior on encounter search page: 
1. when users click at categories, page will scroll to corresponding content
2. when scroll at page content, corresponding category will be highlighted
PR fixes #809
=> 809 update encounter page scroll

pom.xml
manual update of release number
PR does not fix numbered issue
=> prep for 10.5.1 release

README.md
now that we have testing guidelines, reference them in the main readme
PR fixes N/A
=> add testing reference

.github/pull_request_template.md
Current PR template gets ignored. simplified change list and added a finalization checklist instead
PR does not fix a numbered issue
=> Update PR template to include NFRs

src/main/java/org/ecocean/EncounterQueryProcessor.java
no related issue.
* dangling shepherds closed
=> close shepherds that were being left open

src/main/java/org/ecocean/Base.java, src/main/java/org/ecocean/Encounter.java, src/main/java/org/ecocean/Occurrence.java
- prevent backgrounding of encounter indexing on deep index (following pattern in occurrence and individual)
- small fix on redundant rollback/closure
=> no longer background encounter indexing itself

src/main/java/org/ecocean/Encounter.java
[Plain-text summary description of the solution. Include any class updates, new or edited functions, significant changes to UX, etc]
PR fixes #[954]
**Before you Submit!**
* Is all the text internationalized?
* If you made a change to the header, did you update the react, jsp, and html?
* Are all depedencies at a locked version?
* Did you adhere to [best practices](https://wildbook.docs.wildme.org/contribute/code-guide.html)?
* Is there a quick [unit test](https://wildbook.docs.wildme.org/contribute/tests.html) you can add?
=> backend change to add Index Noticable Scarring field so it is searchable

src/main/resources/bundles/locationID.json
Replace UUIDs with human-readable names
=> Seal UUID to location ID update - locationID.json

src/main/webapp/encounters/encounter.jsp
Hello
Please review my changes.
Thank you
=> Removing Twitter and Facebook share

pom.xml
=> version bump for 10.6 release

src/main/resources/bundles/locationID.json
Replace region IDs with human-readable names.
=> Update locationID.json for Sharkbook

src/main/java/org/ecocean/api/UserInfo.java
Ensures this Shepherd gracefully closes the DB connection on exception.
=> Ensure Shepherd closes on exception

frontend/src/AuthenticatedSwitch.jsx, frontend/src/UnAuthenticatedSwitch.jsx
apply page-level code splitting, only build pages when they are needed
PR fixes #1001
=> apply page-level code splitting

pom.xml, src/test/java/org/ecocean/shepherd/core/ShepherdTest.java
Adds mockito to pom and a class for testing interaction with basic Shepherd db transaction methods.
=> Basic Shepherd transaction testing

pom.xml, src/main/java/org/ecocean/shepherd/core/Shepherd.java, src/test/java/org/ecocean/shepherd/core/ShepherdTest.java
- Removes some encounter CRUD methods from the Shepherd class that were found to be unused. 
- Fixes a package mistake in ShepherdTest 
- updates the mockito version in pom.xml
=> Removing unused encounter methods from shepherd

src/main/java/org/ecocean/servlet/EncounterSetSex.java, src/main/java/org/ecocean/servlet/EncounterSetString.java, src/main/java/org/ecocean/servlet/EncounterSetTapirLinkExposure.java, src/main/java/org/ecocean/shepherd/core/Shepherd.java
Removes some occurrence and user CRUD methods from the Shepherd class that were found to be unused.
=> Removing more unused encounter methods from shepherd

src/main/java/org/ecocean/shepherd/core/Shepherd.java, src/test/java/org/ecocean/shepherd/entity/IndividualTest.java
More Shepherd methods that had no discernable use were removed.  This should have no impact on behavior, performance, etc. 
(Removed a few test stubs too ... methods are gone so no need to implement the tests.)
=> Yet more Shepherd method cleanup 

src/test/README.md
1. update test README regarding frontend test command change
2. add testing utilities and examples
=> Update test README

src/main/java/org/ecocean/Annotation.java
Prioritizes matchAgainst=true annotations when background Open Search indexing
=> prioritize matchAgainst=true annotations when background Open Search indexing

devops/deploy/.dockerfiles/tomcat/commonConfiguration.properties
Update prod mail settings in commonConfiguration.properties.
=> localhost -> smpt

pom.xml
=> You're it!

src/main/webapp/header.jsp
header.jsp was throwing a searchbar-related exception when the user was logged out. This silences the error by making sure the searchbar is present before calling any JS logic.
=> Fix JS exception in the header.jsp searchbar when the user is logged out

pom.xml
=> Bump version for 10.7.2

src/main/resources/bundles/locationID.json
Fixed discrepancies between name and id fields.
Added new location for United States and sub-locations.
PR fixes #711
=> Update locationID.json for Amphibian and Reptile Wildbook

src/main/java/org/ecocean/servlet/OccurrenceCreate.java
PR fixes #1057 
do not replace spaces in occurrenceID
=> do not replace spaces in new name (id) for Occurrence

src/main/resources/bundles/locationID.json
Fixed id and name field discrepancies.
PR fixes #711
=> Update locationID.json for MantaMatcher

pom.xml
* Is there a quick [unit test](https://wildbook.docs.wildme.org/contribute/tests.html) you can add?
No.
=> version 10.8.0

src/main/resources/bundles/commonConfiguration.properties
removed "calf" from life stages and replaced with "sub-adult"
PR fixes https://github.com/WildMeOrg/Wildbook/issues/1262
=> Encounter lifestage snails update

frontend/src/pages/BulkImport/BulkImportStore.js
fix giraff species issue caused by the space between 2nd and rd parts of species
=> fix giraff species issue
