src/main/java/org/ecocean/ShepherdPMF.java
src/main/java/org/ecocean/servlet/ServletUtilities.java

I added code to the ShepherdPMF.java module to use environment variables, or Docker secrets, or Kubernetes secrets for the Wildbook Database connections parameters:
datanucleus.ConnectionURL
datanucleus.ConnectionUserName
datanucleus.ConnectionPassword
This allows folks to deploy Wildbook in docker containers with docker-compose, docker stack deploy, or Kubernetes deployments very easily and securely.  No need to edit the jdoconfig.properties file and "rebuild" the war file.  See example below.
I've added lots of comments in the ShepherdPMF.java module.
The setup of the environment variables and secrets in done in a Tomcat **setenv.sh** script.
If the required variables are not exported then the jdoconfig.properties values are used.
```bash
$ echo "wildbook" | docker secret create …
```

Added code to be able to use environment variables and docker/kubernetes secrets for the db credentials

---

src/main/java/org/ecocean/ShepherdPMF.java

I have added support to the ShepherdPMF.java module to also allow the Database Driver Name to be specified as a environment variable and secret.

Added support for the Database Driver Name to be specified as a environment variable and secret

---

src/main/webapp/individualSearchResultsAnalysis.jsp
src/main/webapp/javascript/bubbleDiagram/coOccurrenceGraph.js
src/main/webapp/javascript/bubbleDiagram/encounter-calls.js
src/main/webapp/javascript/relationshipDiagrams/forceLayoutAbstract.js
src/main/webapp/javascript/relationshipDiagrams/graphAbstract.js
src/main/webapp/javascript/relationshipDiagrams/jsonParser.js

The CoOccurrence graph now displays explicit occurrences in addition to the previous links derived from spatial/temporal thresholds and encounters.
As pictured above, all links display a numeric count describing the number of spatial/temporal threshold derived "occurrences" which exist. Additionally, if an explicit occurrence exists, the corresponding link will feature an asterisk and prove unfilterable (though the "occurrence" count will still change). Let me know if you have any ideas for more intuitive ways to notify the user of the explicit occurrences. I played around with some different text colors/link styles but found the contrast lacking.
Additionally, the global species SocialGraph was fixed.
As you may observe, there is still no guarantee that all explicit occurrences will be …

Implemented explicit occurrence links for the CoOccurrence graph

---

src/main/webapp/individualGallery.jsp
src/main/webapp/queue.jsp
src/main/webapp/utick.jsp

A few `myShepherd.closeDBTransaction();`s for less memory leakage. In particular not sure of the effect this has on utick.jsp, since I don't know what that does.

close shepherd in a few jsps

---

src/main/java/org/ecocean/MarkedIndividual.java
src/main/java/org/ecocean/Occurrence.java

A few simple changes that fix/improve patching individuals and sightings/occurrences from Houston.
Individuals: we'd previously been looking for the e.g. `decimalLongitude` key's value on a PATCH call, when the key is actually `value`, and `decimalLongitude` appears as a value itself, under the `path` key. Honestly, just looking at the diff is going to make more sense than my explanation here, haha.
Sightings: all I did was change the read logic so that we'll return just lat or just lon if only one of those is set. It is admittedly weird when there's only one set, but the frontend should be able to see that scenario so they can fix it.
NOTE: we shouldn't merge this until we figure out what's the deal with the default sex value in MarkedIndividual.java. If we leave it as "null", we have to …

Ng patch fixes

---

src/main/java/org/ecocean/ia/IA.java
src/main/java/org/ecocean/servlet/IAGateway.java

when a child (annotation) sub-task fails to run as identification, it is requeued as its own job, so it can be tried again.

ident job requeue fix

---

src/main/webapp/imports.jsp

orgadmins had admin-level ability to view bulk import summaries. We want to restrict them to only see the summary information of the bulk imports they have access to
Reported issue:
https://community.wildme.org/t/orgadmin-role-sees-non-org-members-non-collaborators-in-list-of-bulk-imports/2511/3

drop orgadmin from adminmode for imports

---

src/main/java/org/ecocean/servlet/ProjectUpdate.java
src/main/java/org/ecocean/servlet/ServletUtilities.java

Allow public encounters to be added to projects
PR fixes #329 
**Changes**
- allow broader access to public encounters for all logged in users
- specifically allow public encounters to be added to projects
- better check project access via username (not comparing user objects)

Allow public encounters to be added to projects and more broadly viewed

---

src/main/webapp/pictureBook.jsp

The 'pictureBook-images' div element in pictureBook.jsp had CSS display style 'inline-block', this was changed to 'inline' to fix the issue.
PR fixes #273
**Changes**
- CSS display style changed from 'inline-block' to 'inline' for 'pictureBook-images' div element.

Picturebook image fix

---

src/main/java/org/ecocean/security/Collaboration.java

Allows users with the orgAdmin role to dynamically receive an edit-level Collaboration with anyone in their organization. The collaboration is one-way, and only the orgAdmin should dynamically receive it to get full access permissions. users without orgAdmin role do not get a collaboration with their orgAdmin dynamically.

Org admin broader collab

---

src/main/java/org/ecocean/MarkedIndividual.java
src/main/java/org/ecocean/StartupWildbook.java
src/main/webapp/header.jsp

This PR moves the names cache initialization (e.g., looking up individuals by name) to a better location where it will only be initialized once. This prevents the rare issue of Wildbook lockup when there is heavy traffic on Tomcat restart.

Names Cache: call onces and prevent rare lockup on restart

---

src/main/webapp/individualSearchResults.jsp
src/main/webapp/individuals.jsp
src/main/webapp/javascript/bubbleDiagram/encounter-calls.js

Event button and meta key used to differentiate between various clicks and open the links accordingly on the Individuals page. AuxClick event handling added for middle-click on browsers such as Chrome. Content within one of the columns (which is expected to have unique values) wrapped within an anchor 'a' element for users to right-click and open links on a new tab. Some of the existing anchor 'a' elements on the page had target = '_blank' attribute, this has been excluded for the links to show standard link behaviour as expected.
PR fixes #365 
**Changes**
Functions added: encountTableAuxClick and cooccurTableAuxClick on individuals.jsp 
Functions edited: getData, getEncounterTableData, goToEncounterURL, goToWhaleURL, makeTable, makeRelTable on encounter-calls.js and doTable, rowClick on …

#365 Individuals page link interactions

---

src/main/webapp/javascript/bubbleDiagram/encounter-calls.js

Individual UUID appended to display name in id variable. The UUID is then split later on, so that the 'Occurring With' column shows only the display name as before, while the UUID is used to set the 'class' attribute which is used to form the URL for the cooccurrence table link.
PR fixes #410 
**Changes**
- Edited Functions: getIndividualIDFromEncounterToString, getData and makeTable in encounter-calls.js

Cooccurance table link fixed

---

src/main/java/org/ecocean/importutils/RowFeedback.java
src/main/java/org/ecocean/importutils/TabularFeedback.java
src/main/java/org/ecocean/servlet/importer/StandardImport.java
src/main/webapp/import/uploadFooter.jsp

This PR addresses missing or unsupported species columns (Encounter.genus and Encounter.specificEpithet) in bulk import spreadsheets. However, it lays the foundation for reporting errors in other fields as well and blocking submission where data is missing.
Specifically:
- Adds method RowFeed.logParseError(int colNum, Object value, Row row, String exactMessageToDisplay) for more informative error messages via parameter exactMessageToDisplay
- Adds an Errors section to the Import Overview preview
- Provides a count of total errors in the spreadsheet, which can include missing images and incorrect species currently
- Throws an error if Encounter.genus and/or Encounter.specificEpithet are blank or empty strings
- Throws an error if Encounter.genus and Encounter.specificEpithet form a …

Bulk import validation - species

---

src/main/java/org/ecocean/ia/Task.java
src/main/java/org/ecocean/identity/IdentityServiceLog.java
src/main/webapp/iaLogs.jsp
src/main/webapp/iaResults.jsp

This change improves iaResults.jsp page display speed while reducing unnecessary traffic to and burden on WBIA. Wildbook knows when a matching Task is complete but was still sending multiple completion status queries to WBIA per page load for completed tasks, causing significant and unnecessary page load slow downs. This change now checks for Task object completion (either its own completion time is set or all completion times are set for all sub-Task node children) in the database before querying WBIA about Task status. For incomplete tasks, queries are still sent.

Remove unneeded wbia call

---

src/main/java/org/ecocean/servlet/TissueSampleSetHaplotype.java
src/main/java/org/ecocean/servlet/export/KinalyzerExport.java

This PR:
- Filters the genetics export to only the loci found on matching individuals
- Fixes a bug that prevented propagation of Haplotype to the MarkedIndividual in some cases

Genetics Export: Filter Loci to Only Those Found in the Result Set

---

src/main/webapp/iaResults.jsp

The clickable element did not have a target attribute while opening the URL. The target attribute has been passed, for the clickable element to show standard link behaviour. Also, all links on the page had target = "_new" attribute. This has been excluded for the internal links, for them to show standard link behaviour.
PR fixes #366
**Changes**
- New functions: rowClick and Edited Functions: displayAnnotDetails in iaResults.jsp
- Callout: The menu which opens upon right-clicking on the clickable element does not show the 'Open link in new tab' option. Only an anchor 'a' element shows this. The anchor elements within the clickable element can be right-clicked to open in new tab. This was called out previously in earlier PRs while applying a similar fix on other pages.

Match results page links fixed

---

src/main/java/org/ecocean/servlet/importer/StandardImport.java

Validation tweak on previous validation changes for this release: this ensure that an empty Encounter.mediaAssetX column does not create a blocking error. Still blocks if there is a value (filename) and it cannot be found.

Makes an empty MediaAsset column a non-blocking validation.

---

src/main/webapp/encounters/manualAnnotation.jsp

Additional logic to ensure that if you draw a part on top of an image that already has another part then the new part is forced onto a separate encounter. This primarily addresses the use case of many finned species in which we only allow drawing fin parts, such that every additional part is the fin of another individual.

Added use case where a second part on an image forces a cloned Encounter

---

src/main/java/org/ecocean/servlet/OccurrenceAddEncounter.java
src/main/java/org/ecocean/servlet/OccurrenceCreate.java

Error messages around sighting ID management were causing confusion in support case; cleaned up to clarify the failure state. Still need to be extracted out for localization
PR fixes #453
**Changes**
- copy change for Create Sighting ID failure message
- copy change for Failure to find Sighting ID message

cleaned up sighting managment error messages

---

src/main/java/org/ecocean/Shepherd.java
src/main/java/org/ecocean/servlet/UserCreate.java

The logic which appends context to roles has been excluded for Login Success (`/LoginUser`) and User Confirmation (`/UserCreate`) pages.
PR fixes #423

Display roles without context on login user page

---

src/main/java/org/ecocean/ShepherdProperties.java

This PR updates ShepherdProperties.loadProperties to load paths relative to the Tomcat install rather than relative to the current working directory. While these are often the same, it is possible that the process will have an arbitrary current working directory, such as when running Tomcat manually or when using the macOS Homebrew service.
Fixes #504.
**Changes**
- Uses `System.getProperty("catalina.home")` to get the Tomcat install path. This is more reliable than using the CWD.
- The Java `Path` API is used for resolution.
- I went ahead and fixed some warnings in the edited function and added documentation to it.
- I've tested this on my Mac but I haven't checked if it works on Linux; I don't have any other computers running Tomcat.

fix(ShepherdProperties): always load relative to `catalina.home`

---

src/main/java/org/ecocean/ShepherdProperties.java

Reverts WildMeOrg/Wildbook#505; ticket caused breaking changes

Revert "fix(ShepherdProperties): always load relative to `catalina.home`"

---

src/main/java/org/ecocean/MarkedIndividual.java
src/main/java/org/ecocean/api/Login.java
src/main/webapp/encounters/relatedIndividuals.jsp
src/main/webapp/javascript/bubbleDiagram/encounter-calls.js
src/main/webapp/javascript/relationshipDiagrams/jsonParser.js
src/main/webapp/javascript/relationshipDiagrams/socialGraph.js

1. now relationship diagram displays relationships between individuals
2. relationship table displays individual's link, name, etc

fix relationship diagram and relationship table display issue

---

src/main/java/org/ecocean/media/AssetStore.java
src/main/java/org/ecocean/media/LocalAssetStore.java
src/main/java/org/ecocean/media/MediaAsset.java
src/main/java/org/ecocean/resumableupload/UploadServlet.java
src/main/java/org/ecocean/servlet/EncounterForm.java
src/main/java/org/ecocean/servlet/MediaAssetCreate.java
src/main/java/org/ecocean/servlet/export/EncounterSearchExportMetadataExcel.java
src/main/java/org/ecocean/servlet/importer/StandardImport.java
src/main/webapp/encounters/encounter.jsp
src/main/webapp/encounters/encounterMediaGallery.jsp
src/main/webapp/iaResults.jsp
src/main/webapp/import/reviewDirectory.jsp
src/main/webapp/obrowse.jsp

addresses #412 
- creates new (optional) MediaAsset parameter `userFilename` to store filename as user provided it
- `asset.getUserFilename()` added, defaults to `getFilename()` when above unset
- added to standard MediaAsset json output
- utilized in various UI elements from original issue:
**Export**
**Encounter image gallery**
**obrowse**

display original user-supplied filename in various capacities

---

src/main/java/org/ecocean/servlet/MediaAssetAttach.java

adds a message to audit trail comment when a MediaAsset is added to Encounter.
PR fixes #414

Added encounter's audit trail when adding image

---

src/main/webapp/encounters/manualAnnotation.jsp

'none configured' added to the iaClass dropdown for manual annotation, with the value 'none_configured'.
PR fixes #248
**Changes**
- Callout: The fix for this issue is the 'if condition' starting from line 238 which adds 'none configured' to the iaClass dropdown if there are no iaClasses configured for the species. While fixing this issue, another issue was seen. There was a fix applied previously to have the default viewpoint '---------' option selected while navigating to the page, but the option to select iaClass wasn't getting displayed by default. This issue has also been fixed in this PR by excluding the viewpoint null check since there will always be a default value for the viewpoint.

Manual Annotation without iaClass configured

---

src/main/java/org/ecocean/servlet/importer/StandardImport.java

Subspecies are defined in commonConfiguration.properties with an _. For example:
genusSpecies0 = Giraffa tipperskirchi_thornicrofti
Subspecies validation was failing because users enter the species without the underscore. This change removes the _ so that validation can proceed and users don't have to know about the weird configuration required.
PR fixes #559 
**Changes**
- removes the _ from subspecies validation of values in commonConfiguration.properties

Supports species validation with subspecies

---

src/main/resources/bundles/contexts.properties

Restores existing version-setting capability already used and working in pom.xml via Maven.
PR fixes #458
**Changes**
- allows ${pom.version} to be replaced in any piece of code during the Maven build and substitute with the version number (e.g., 10.2) defined in pom.xml. This already existed and worked but simply fell out of use. This commit restores it to the place where it is  then called in footer.jsp but should be usable anywhere within the view of the Maven build.

Dynamically set Wildbook version via pom.xml Maven build

---

frontend/src/FrontDesk.jsx
frontend/src/GoogleTagManager.jsx
src/main/java/org/ecocean/CommonConfiguration.java
src/main/java/org/ecocean/servlet/JavascriptGlobals.java
src/main/java/org/ecocean/servlet/ServletUtilities.java
src/main/resources/bundles/googleKeys.properties
src/main/resources/servletResponseTemplate.htm
src/main/webapp/header.jsp

fixes issue #582 
add stonely widget to react pages head

582 stonely widget in react header

---

src/main/webapp/iaResults.jsp
src/main/webapp/iaResultsAnnotFeed.jsp

Whiskerbook users uncovered some edge cases where unanticipated null values could cause failure to display match results. A pair of JavaScript and Java errors were thrown and are patched here. General exception handling should be useful across all branches.
**Changes**
- Better null Encounter number handling in iaResults.jsp JavaScript. 
- Better null handling in java in iaResultsAnnotFeed.jsp

FIX: weird null behavior

---

src/main/java/org/ecocean/LocationID.java
src/main/webapp/import.jsp

Restores auto-selection of the bulk import-specific locations IDs, properly scoping ID requests as a result when they are sent from the bulk import's page. The lack of this has caused overscoped matching in Wildbook and much slower, very large jobs in WBIA.
**Changes**
- Allows for multi-selection of the generated HTML for the locationID selector based on a passed in list of 0 or more location IDs. Retains single locationID selection.
- Restores scoped location ID selection by default to the location ID pulldown for matching on the bulk import page. Multiple locationIDs in the bulk import Encounters result in each locationID being included in the default scope

Restore default locationID selection to bulk import

---

pom.xml

verifying that all dependencies are locked to a specific version as well as cleanup of commented out dependencies and configuration duplication that could lead to problems down the road
PR fixes #595 
**Changes**
- linting
- cleaned out commented out dependencies
- cleared out maven compiler configuration that is duplicate of the global project setting
- cleared out duplicate io.prometheus dependencies

format and cleanup; version verification

---

src/main/webapp/appadmin/admin.jsp
src/main/webapp/appadmin/locationIDTester.jsp
src/main/webapp/submit.jsp

a change to `LocationID.java` introduced a new variation of the method `getHTMLSelector()` which created ambiguous call from a few jsp pages. these were fixed by casting null to a string.

fix broken calls to getHTMLSelector()

---

src/main/java/org/ecocean/servlet/ServletUtilities.java

template code would throw a null pointer exception when username was null (e.g. user not logged in).

bugfix: template can cause NPE

---

src/main/webapp/encounters/i3sScanEndApplet.jsp

I3S results page throws a persistent NullPointerException that interferes with other support and logging. Hushing the exception through better exception handling.
**Changes**
- Better null checking and handling to avoid the exception

Silence high traffic I3S exception with better exception handling

---

src/main/java/org/ecocean/Annotation.java

Where >1 location ID scopes an ID query (e.g., (enc.locationID=='place1') || enc.locationID=='place2' )), query completion time rises dramatically (e.g., 1 sec. -> 180 seconds). due to inefficient JDOQL -> SQL translation by DataNucelus. Changing to "literal" scoping produces approx. 100-1000x improvement in query execution time by reducing query complexity and leveraging in memory comparison.
**Changes**
- ID query building now leverages literals for location ID

More efficient query (faster) where multiple location IDs scope the ID query

---

src/main/java/org/ecocean/ia/plugin/WildbookIAM.java

Wildbook is comparing lists of annotations with WBIA on building every ID job. This is excessive, and even if they are out of sync, Wildbook sends the small difference after checking. Using caching, this comparison process is sped up 95%, allowing Wildbook to send ID jobs to WBIA much more quickly and reducing request traffic to WBIA that is competing with actual ID job execution for resources.
**Changes**
- adds a cache to the sendAnnotationsAsNeeded process during ID job creation.

Reduce annot comparison time between Wildbook and WBIA by caching

---

src/main/webapp/iaResults.jsp
src/main/webapp/iaResultsNoMatch.jsp

PR fixes #598 
when match results are presented to a user _without a project filter_, this allows a user to click "Confirm No Match" button and create a new individual with a name they provide.

fix dead-end for "confirm no match" button without project

---

pom.xml

library version update for rabbitmq (based on dependabot [PR473](https://github.com/WildMeOrg/Wildbook/pull/473))

version change for rabbitmq lib

---

src/main/java/org/ecocean/api/Login.java

Login.java defined a long session timeout that overrides the default in web.xml. This commit removes the single line of code that restores the default, expected timeout.
PR fixes #690 
**Changes**
- Removes code line overriding default session timeout

Prevent login from overriding session timeout defined in web.xml

---

src/main/webapp/header.jsp

Switches the timeout modal popup to use /react/login/ versus the old, deprecated /welcome.jsp.
PR fixes #699 
**Changes**
- Switch a single Javascript reference from /welcome.jsp to /react/login/

Switch welcome.jsp to /react/login/

---

src/main/webapp/import/instructions.jsp

usability: no red text
otherwise, we refer to bulk import as in beta, not in alpha, everywhere except for the actual bulk import page. Unified messaging is important
PR does not solve a numbered issue

upgraded from alpha to beta

---

frontend/README.md

I'm getting the basic dev environment set up and have a couple fixes/suggestions for the React readme. Please let me know if I've gotten anything wrong, of course.
**Changes**
- Fix the port number in the instructions to match the [default](https://github.com/carllelandtaylor/Wildbook/blob/81c2cb987e8f1d250f70594dcf93014060db68fe/devops/deploy/_env.template#L33) and the [devops readme](https://github.com/carllelandtaylor/Wildbook/blob/master/devops/README.md?plain=1#L35).
- Clarify that the .env file is for React environment variables, and when you use which value for `PUBLIC_URL`.

[react][readme] Update instruction ports to match defaults, clarify PUBLIC_URL

---

frontend/src/components/Map.jsx
frontend/src/locale/de.json
frontend/src/locale/en.json
frontend/src/locale/es.json
frontend/src/locale/fr.json
frontend/src/locale/it.json

fix an issue on map page: changed state(key) did not trigger third party component(react google map) re-rendering, thus map was not updated with key from property files, so map always showed "development use only". updated code will fix this issue. now if key is null(initial value), show a loading status instead of map
PR does not fix a numbered issue

fix google map key issue

---

frontend/src/pages/Login.jsx

update page layout to support medium screen properly

fix login page responsiveness issue

---

src/main/webapp/projects/project.jsp

1. limit the max width of uuid columns to 180px
2. set word-break: break-all to avoid long names taking too much width
3. adjust action buttons' width to take up width of the whole column on medium and smalm screen
PR fixes #732

adjust project table column width

---

src/main/java/org/ecocean/Base.java
src/main/webapp/pictureBook.jsp

pictureBook.jsp:
- did not check every relevant field for tissue samples and satellite tags but rather only looked at legacy dynamic properties
- mislabeled Encounter.alternateID as "Nickname"
- did not mention that listed encounters were limited to N-most recent
**Changes**
- Improved description in pictureBook.jsp
- Improved checks to support dynamic properties (legacy) and TissueSample and SatelliteTag data objects (newer, preferred)
- Changed Encounter "Nickname" coulmn to "Alternate ID" (often field IDs)

Improve picture book lookup, limits, and description

---

src/main/webapp/appadmin/editAssetStore.jsp

Default asset store config was not a good example for Dockerized Wildbook
**Changes**
- Provide a Docker-compatible example for users

Migrate default config to Dockerized example

---

src/main/resources/bundles/commonConfiguration.properties

Watermark reference in Image Majick reference uses non-Dockerized path.
**Changes**
- Change commonConfiguration.properties to use the watermark path in the new Dockerized Wildbook

Make sure watermark reference uses dockerized path

---

frontend/src/FrontDesk.jsx
frontend/src/components/SessionWarning.jsx
frontend/src/constants/sessionWarning.js
frontend/src/locale/de.json
frontend/src/locale/en.json
frontend/src/locale/es.json
frontend/src/locale/fr.json
frontend/src/locale/it.json

implement same session expire warning as jsp pages.
some points worth noting:
1. when countdown ends, the page shows user is logged out, and was prompted to login again, actually user is not logged out, the session expire warning is not  tied with actual tomcat user session
2. even if the user remains active on the page, when the set time is reached, the modal will still appear if the page hasn’t been refreshed during that time. although it's unlikely for a user to stay on the same page for 20 minutes without navigating away.
3. if the user clicks the close button, the modal will not reappear when the 20 minutes are up, as long as the page isn’t refreshed.

647 session warning react

---

frontend/maven-build.sh

add npm ci in maven-build.sh to ensure all dependencies are installed before building frontend
PR does not fix a numbered issue

install frontend dependencies before building

---

frontend/src/FrontDesk.jsx
frontend/src/UnAuthenticatedSwitch.jsx
frontend/src/locale/de.json
frontend/src/locale/en.json
frontend/src/locale/es.json
frontend/src/locale/fr.json
frontend/src/locale/it.json
frontend/src/models/auth/useLogin.js
frontend/src/pages/Login.jsx
src/main/java/org/ecocean/api/Login.java

This PR allows a Wildbook URL to a secured endpoint to be entered and then redireted back to after login.
For example, /appadmin/dataIntegrity.jsp is secured, and a public request to it should be redirected to /react/login/ before returning the user to /appadmin/dataIntegrity.jsp.
PR fixes #675 
**Changes**
- remove call to /Collaborate if user is not yet logged in. This interferes with our ability to get the redirect URL.
- remove call to /UserGetNotifications if user is not yet logged in. This interferes with our ability to get the redirect URL.
some test points:
1. login/logout normally
2. access protected jsp pages in logged out state, e.g. /individualSearchResults.jsp?username=test  etc
3. access protected react pages in logged out state, e.g. …

expose redirect URL from Apache Shiro back to React

---

frontend/src/UnAuthenticatedSwitch.jsx
frontend/src/models/auth/useLogin.js

when redirecting user to the url after login, we first encode the url and send to login page, then decode the ulr before redirecting, this handles some complex cases such as url with special characters, so that the url won't  be truncated.
PR does not fix a numbered issue

optimizations for redirecting ticket

---

frontend/src/App.jsx

PUBLIC_URL could be relative path or a full url, so it has to be dealt with differently
if PUBLIC_URL="/react/", use it directly, if it's a full url, parse it and get the path name

update update_url to suit different path

---

frontend/src/models/auth/useLogin.js

when building redirect url in useLogin.js, no need to parse it to get path name. we can use it directly

10.4 patch public url part 2

---

frontend/src/FrontDesk.jsx
frontend/src/pages/ReportEncounter.jsx

ISSUE: #744 
- SignIn banner will visible only when user is not logged in
- after clicking sign in from the banner and succussful login, redirecting back to report encounter page

[ISSUE-744] Sign In Banner Update

---

frontend/src/components/FollowUpSection.jsx
frontend/src/pages/ReportsAndManagamentPages/ReportEncounter.jsx
frontend/src/pages/ReportsAndManagamentPages/ReportEncounterStore.js
frontend/src/pages/ReportsAndManagamentPages/SpeciesSection.jsx

PR fixes: #795 
added followup information frame and email validation

[795] information frame

---

devops/development/docker-compose.yml
pom.xml

change needed so maven can compile on servers
PR fixes #839 
**Changes**
- maven war plugin version change
- lock opensearch docker image version

pom.xml fix for servers (and lock in opensearch version)

---

src/main/java/org/ecocean/identity/IBEISIA.java

Fixes the situation where Encounter cloning (>1 animal in photo) and multi-algorithm matching cause only one algorithm's results to be shown rather than all algorithms.
PR fixes #632 
**Changes**
- Switch IBEISIA to use Encounter-based annotation submission to the matching queue. previously it was all annotations across the original and cloned Encounter.

Fix Encounter single submission multi-algorithm, cloneEncounter bug

---

src/main/java/org/ecocean/Encounter.java

The is allows submitters, photographers, and informOthers to be correctly searched in Encounter Search
**Changes**
- Sets keywordNormalType for three fields: submitters, photographers, and informOthers

Add submitters, photographers, and informOthers to keywordNormalType

---

devops/deploy/.dockerfiles/tomcat/commonConfiguration.properties
devops/development/.dockerfiles/tomcat/commonConfiguration.properties
src/main/java/org/ecocean/CommonConfiguration.java
src/main/resources/bundles/commonConfiguration.properties
src/main/webapp/submit.jsp

projects dropdown now displays conditionally if the user has projects to access. does not display anonymously
PR fixes #280 
**Changes**
- cleaned up display so field matches overall page
- hide/display based on projects available to be added to
- removed configuration options and related code that causes a default project to be selected as it was unused (confirmed across production) and messy

Projects hide

---

src/main/webapp/iaResults.jsp

iaResults had some (likely accidental) `` comment wrappers around the whole file. apparently was breaking page functionality.
* does not have a corresponding issue

clean up comment brackets in iaResults

---

src/main/java/org/ecocean/servlet/export/EncounterAnnotationExportExcelFile.java

On investigation, found that lifestage and sex were both pulling from individual. addressed both to avoid future confusion and grouped fields logically
PR fixes #862 
**Changes**
- relabeled the final state info from the individual
- grouped differently to be clearly associated with individual
- added encounter-specific life stage and sex

annotation export: regrouped/labeled ind info, added enc info

---

frontend/src/AuthenticatedSwitch.jsx
frontend/src/FrontDesk.jsx
frontend/src/UnAuthenticatedSwitch.jsx
frontend/src/components/AuthenticatedAppHeader.jsx
frontend/src/components/UnAuthenticatedAppHeader.jsx
frontend/src/components/header/Menu.jsx
frontend/src/constants/navMenu.js

based on showclassicsubmit from /site-settings, show/hide the old report encounter page on both authenticated header and unauthenticated header

Toggle old report an encounter page

---

frontend/src/pages/ReportsAndManagamentPages/PlaceSection.jsx

remove the “version: weekly" option from loader so the map won't be loaded twice with different options(which will cause map display issue)
PR does not fix numbered issue.
Test cases:
check the place section of encounter submission page, check the two maps: 1. below location ID select 2. inside location ID select dropdown, all maps should show correctly

fix two different options for map loaders issue

---

frontend/src/components/Map.jsx
frontend/src/components/filterFields/LocationFilterMap.jsx

The map component previously used hardcoded values for the center and zoom settings. It now retrieves this data dynamically from the /api/v3/site-settings endpoint, allowing for platform-specific configurations.
PR fixes #802

map use center and zoom data from /site-settings

---

eslint.config.mjs
frontend/config-overrides.js
frontend/config/webpack/webpack.dev.js
frontend/config/webpack/webpack.prod.js
frontend/src/AuthenticatedSwitch.jsx
frontend/src/components/AuthenticatedAppHeader.jsx
frontend/src/components/Form/LabelledKeywordFilter.jsx
frontend/src/components/Link.jsx
frontend/src/components/UnAuthenticatedAppHeader.jsx
frontend/src/constants/navMenu.js
frontend/src/hooks/useFetch.js
frontend/src/pages/ReportsAndManagamentPages/ImageSection.jsx
frontend/src/pages/ReportsAndManagamentPages/ReportEncounter.jsx
frontend/src/pages/ReportsAndManagamentPages/ReportEncounterStore.js
frontend/src/service-worker.js
frontend/src/serviceWorkerRegistration.js
frontend/src/utils/formatters.js
package-lock.json
package.json

Reworks eslint config to remove existing errors, and eslint ignore blocks
PR fixes #867
**Changes**
- rework eslint config
- fix any existing errors
- remove eslint ignore blocks and resolve related issues
- added TODOs for unused variables to confirm if they should be kept 
**Notes**
- My editor is configured to auto-fix style issues on save, let me know if that's obnoxious (there's a lot of spacing / formatting updates in here because of that) 
- When running `mvn clean install` eslint errors are still being reported, it seems that when `react-app-rewired` is being temporarily installed during the install it's using its own eslint config that doesn't match what we have here. I am unfamiliar with that package and am not sure how to overwrite it to use our own, but am open to any ideas …

Fix #867 ESLint Config

---

frontend/src/service-worker.js

This PR addresses an ESLint issue in service-worker.js by adding a directive (/* eslint-disable no-restricted-globals */) to prevent linting errors related to the use of self, which is required in the Service Worker context. 
PR does not fix a numbered issue.

add eslint-disable-line to prevent restricted globals error

---

src/main/java/org/ecocean/Encounter.java

bugfix on search permissions calculations
PR does not address issue
* admin users still need to build list of collaborations for later permissions computation

bugfix: dont skip admins in our creation of collab structure

---

frontend/src/components/DataTable.jsx
frontend/src/pages/EncounterSearch.jsx
src/main/java/org/ecocean/Encounter.java
src/main/java/org/ecocean/EncounterQueryProcessor.java
src/main/java/org/ecocean/OpenSearch.java
src/main/java/org/ecocean/api/SearchApi.java

search results allow user to see minimal results for matches they do not have access to
PR fixes #958 
- Do not limit query based on permissions
- API:
- Return all results, with inaccessible ones containing only minimal fields
- New field `access` can be used to stylize/filter results based on user permissions
- EncounterQueryProcessor: only allow items with access (skip inaccessible)

search result changes to allow inaccessible results 

---

src/main/java/org/ecocean/servlet/IndividualRemoveEncounter.java
src/main/java/org/ecocean/servlet/OccurrenceRemoveEncounter.java

This indexing is duplicative (the Shepherd.commitDBTransaction() should index the Encounter) and has been reported as blocking prompt execution.
https://community.wildme.org/t/sharkbook-bug-cannot-remove-identity-from-a-particular-encounter-and-delete-it/4546/2
Removing shows correct indexing and makes the servlet (IndividualRemoveEncounter) speedy again.

Remove an unnecessary and functional blocker indexing line

---

src/main/webapp/encounters/encounterSearch.jsp
src/main/webapp/encounters/searchResults.jsp

Previous string replacement seems to have replace some Strings that were functionally part of legacy Encounter Search. This fixes that and is necessary for legacy Encounter Search to reach its corresponding results page.

Restore Encounter Search pathing while legacy Encounter Search is temporatily supported

---

frontend/src/FrontDesk.jsx

favIcon should be consistency across the site. call useDocumentTitle hook in FrontDesk.jsx so all react pages use the same favIcon from /api/v3/site-settings
PR fixes #952

fix react favIcon inconsistency issue

---

frontend/src/hooks/useDocumentTitle.js
src/main/java/org/ecocean/api/SiteSettings.java

react pages should have the same meta description, key words and author info as jsp pages do do for better SEO.
now we get them from commonConfiguration properties.

950 add meta description in react

---

src/main/java/org/ecocean/Annotation.java
src/main/java/org/ecocean/Base.java
src/main/java/org/ecocean/Encounter.java
src/main/java/org/ecocean/MarkedIndividual.java
src/main/java/org/ecocean/Occurrence.java
src/main/java/org/ecocean/OpenSearch.java
src/main/java/org/ecocean/Shepherd.java
src/main/resources/org/ecocean/package.jdo
src/main/webapp/appadmin/opensearchInfo.jsp
src/main/webapp/appadmin/opensearchSync.jsp

Indexing on Annotations
PR fixes #873 
**Changes**
- Annotation now inherits from Base
- add `version` to Annotation
- Annotation index mapping and serializer
- some changes to Base.java to allow generalized `opensearchSync()`, e.g. `getById()` and `getAllVersionsSql()`
- `opensearchSync()` pulled out of Encounter.java and put into Base.java, see above
- corresponding changes to MarkedIndividual and Occurrence due to Base changes (for future indexing of these classes)
- OpenSearch `backgroundStartup()` now includes Annotations in background indexing
- `opensearchInfo.jsp` now genericized to show all valid indices
- `opensearchSync.jsp` utility now genericized to support both Encounter and Annotation indices

873 opensearch indexing annotations

---

src/main/java/org/ecocean/api/GenericObject.java
src/main/webapp/WEB-INF/web.xml

`GET /api/v3/media-assets/ID`
PR fixes #978 
Provides way to get basic info about a MediaAsset using its ID.

basic api GET for MediaAssets

---

src/main/java/org/ecocean/Annotation.java
src/main/java/org/ecocean/api/BaseObject.java
src/main/webapp/WEB-INF/web.xml

`POST /api/v3/annotations` to create a new Annotation.
PR fixes #920 
required (valid) values in payload:
- `mediaAssetId`
- `x`, `y`, `width`, `height` (`theta` is optional; will be 0 if not given)
- `iaClass`
- `viewpoint`
- `encounterId`

Annotation create POST api

---

frontend/package-lock.json
frontend/package.json
frontend/src/AuthenticatedSwitch.jsx
frontend/src/components/AddAnnotationModal.jsx
frontend/src/components/AnnotationSuccessful.jsx
frontend/src/components/ResizableRotatableRect.jsx
frontend/src/components/Slider.jsx
frontend/src/locale/de.json
frontend/src/locale/en.json
frontend/src/locale/es.json
frontend/src/locale/fr.json
frontend/src/locale/it.json
frontend/src/models/encounters/useCreateAnnotation.js
frontend/src/models/js/calculateFinalRect.js
frontend/src/models/js/calculateScaleFactor.js
frontend/src/pages/ManualAnnotation.jsx
src/main/java/org/ecocean/api/GenericObject.java
src/main/webapp/javascript/ia.IBEIS.js

new manual annotation page implemented:
1. "add annotation" links to new manual annotation page
2. user must select iaClass, view point and draw an annotation box before submitting
3. user can draw, delete bounding box
4. user can drag, edit, rotate bounding box
5. user can submit successfully and then will be taken to the new successful landing page

913 manual annotation page

---

src/main/webapp/iaResultsSetID.jsp

The private method setImportTaskComplete can be called repetetively and should not be closing the shared Shepherd database connection it uses. This throws nonblocking but unnecessary and repetetive exceptions. This resolves this by calling the correct Shepherd.updateDBTransaction() method for this use case.

Better Shepherd handling on setting Import Task Complete

---

src/main/webapp/WEB-INF/web.xml

Investigating why users.jsp went from orgAdmin-level access requirement to admin. This simple change restores expected behavior.

Regression: users.jsp should be accessible to orgAdmins

---

frontend/src/components/navBar/MergeMessages.jsx
frontend/src/models/notifications/changeIndividualMergeState.js
src/main/java/org/ecocean/MarkedIndividual.java
src/main/java/org/ecocean/StartupWildbook.java
src/main/java/org/ecocean/scheduled/ScheduledIndividualMerge.java
src/main/java/org/ecocean/security/Collaboration.java
src/main/java/org/ecocean/servlet/MergeIndividual.java
src/main/java/org/ecocean/servlet/ScheduledIndividualMergeUpdate.java
src/main/java/org/ecocean/servlet/UserGetNotifications.java
src/main/resources/org/ecocean/scheduled/package.jdo

[Plain-text summary description of the solution. Include any class updates, new or edited functions, significant changes to UX, etc]
PR fixes #756 
**Before you Submit!**
* Is all the text internationalized?
* If you made a change to the header, did you update the react, jsp, and html?
* Are all depedencies at a locked version?
* Did you adhere to [best practices](https://wildbook.docs.wildme.org/contribute/code-guide.html)?
* Is there a quick [unit test](https://wildbook.docs.wildme.org/contribute/tests.html) you can add?

Issue 756 merge individual automation and notification fixes

---

src/main/java/org/ecocean/Encounter.java

Encounter.verbatimEventDate is being indexed as [date] in OpenSearch. The field is intended to be a freeform text field for non-specific dates. This PR forces OpenSearch to consider it text. previously, date-like entries in the field were causing OpenSearch to try to validate it as a [date] field. This change forces text validation.

Ensure Encounter.verbatimEventDate is indexed as plain text and not date in OpenSearch

---

src/main/java/org/ecocean/Annotation.java

bugfix: parts-based iaClass was not getting handled correctly in opensearch query for matching set.
now uses wildcard to match _trailing end of_ the `iaClass` field when there is a part present.
(this mimics the previous non-opensearch matchingSet logic)

fix for opensearch-based matchingSet query when supporting parts

---

src/main/java/org/ecocean/servlet/LightRestServlet.java
src/main/java/org/ecocean/servlet/RestServlet.java
src/main/java/org/ecocean/shepherd/core/Shepherd.java
src/main/java/org/ecocean/shepherd/core/ShepherdPMF.java
src/main/java/org/ecocean/shepherd/utils/ShepherdState.java
src/main/webapp/dbconnections.jsp
src/test/java/org/ecocean/extensions/StaticFieldClearExtension.java
src/test/java/org/ecocean/shepherd/utils/ShepherdStateTest.java

The ShepherdState functionality which keeps an eye on db transaction begins and commits and is exposed in dbconnections was part of the ShepherdPMF file ... this pr pulls it out into its own file for clarity and adds some tests.

Extract ShepherdState from PMF to its own class

---

src/main/java/org/ecocean/IndividualQueryProcessor.java

fix exception being thrown for malformed sql from jdoql.
PR fixes #320 
after way too much sleuthing and trail-and-error, a comment about jdoql being "sensitive" to clause order, it seems that switching around the order of these leading 2 where clauses fixes the problem.
testing needed, for sure.

fix(?) broken jdo query by swapping around clause order

---

src/main/java/org/ecocean/Annotation.java

When an Encounter has the property `specificEpithet` containing the value `sp`, the annotation matchingSet will be found by matching _any_ taxonomy that starts with the `genus` value only, using this wildcard OpenSearch query clause:
```
"wildcard": {
"encounterTaxonomy": "Genusvalue *"
}
```
PR has no related issue.

special wildcard match on taxonomy when encounter has "sp" for specificEpithet

---

frontend/src/pages/SearchPages/getAllSearchParamsAndParse.js

fix an issue found in 10.6: When a user clicks on My Data > My Encounters > My unapproved animals they get 0 results. But if the same user starts an encounter search and searches for their own unapproved encounters (Metadata > Encounter state is unapproved > Assigned user is username) then the search results actually load a list of their unapproved encounters.
1. search term should be "state" not "status"
2. update formFilters when user search from "my encounter" in nav, so that sidebar can reflect filters from "my encounters" as well
PR does not fix numbered issue

messed-up status/state term

---

src/main/java/org/ecocean/IAJsonProperties.java
src/main/java/org/ecocean/api/SiteSettings.java

PR fixes #1097 
- new method `getAllIAClassesWithParts()` in IAJsonProperties class provides list of IAClasses, inclusive of ones with _parts_
- utilize above in api site-settings output for `iaClass` value
- some incidental linting

include iaClasses with parts in option for manual annotation

---

frontend/src/components/AddAnnotationModal.jsx
frontend/src/models/encounters/useCreateAnnotation.js
frontend/src/pages/ManualAnnotation.jsx

support all-directon drawing on react manual annotation page
(x,y) should always be the top-left corner, width and height should always be positive numbers
top to bottom
bottom to top
left to right
right to left
PR fixes #1096

support all direction drawing

---

frontend/maven-build.sh

Sets the default name in the React header to "Wildbook" from "Test Site Name".

Set React default name to Wildbook

---

src/main/resources/bundles/commonConfiguration.properties

Sets smtp as the default email configuration mailhost.

Set smtp as default email config

---

devops/deploy/_env.template
devops/deploy/docker-compose.yml

This removes the need to update the wildbook container healthcheck url on deployment and also allows removes the hardcoded /data in the volume mapping.

Parameterizing Wildbook base directory and URL in docker-compose.yaml

---

src/main/webapp/cust/mantamatcher/styles/_custom.less

Standardizes JSP div.maincontent top margin to 25px to remove wasted space.
Before:
After:

Standardize and minimize JSP maincontent div margin padding

---

src/main/java/org/ecocean/servlet/MembershipCreate.java
src/main/java/org/ecocean/social/Membership.java
src/main/webapp/individuals.jsp

Display fixes for Social Units as rendered on individuals.jsp.
1. Fix display of wrong start and end dates for social unit membership due to variable scoping
2. Allow for setting start and end date to null
PR fixes #1135

Social unit fixes on individuals.jsp

---

src/main/java/org/ecocean/IAJsonProperties.java
src/main/java/org/ecocean/api/SiteSettings.java

- tweak to `isUserSelectableIAClass()` to allow 2-level taxonomies to return iaClasses but not 3-level taxonomies
- return api json to using `getValidIAClassesIgnoreRedirect()` (which works now thanks to above)

Fix to the fix for 1163

---

src/main/resources/emails/en/collaborationInvite.html

A single character fix to set the correct tag name for replacement in automated collaboration request emails.

Fix @SENDER-EMAIL@ tag name in collaboration emails

---

frontend/src/pages/ManualAnnotation.jsx
src/main/java/org/ecocean/api/GenericObject.java

Fix annotation coordinate mismatch for images with rotationInfo
1. Apply adjustment factors when sending annotation payloads if rotationInfo is present.
2. Reverse the adjustment when rendering existing annotations so they display at the correct position.
Why
Previously, annotations looked correct when drawn but appeared shifted after saving/loading on images with rotation metadata. This fix ensures consistent coordinates between drawing, saving, and rendering.
PR fixes #1146

1146 manual annotation shift

---

src/main/java/org/ecocean/Encounter.java
src/main/java/org/ecocean/EncounterQueryProcessor.java
src/main/java/org/ecocean/IndividualQueryProcessor.java

Allows for normal subspecies definition without the need for an underscore in the genusSpeciesX definition in commonConfiguration.properties.
old way:
genusSpecies0 = Giraffa camelopardalis_camelopardalis
new way:
genusSpecies0 = Giraffa camelopardalis camelopardalis

Store and search subspecies more consistently

---

src/main/java/org/ecocean/shepherd/core/Shepherd.java

Handles a weird edge-case in which an ImportTask can have a null User assigned and passes it into this function as a null User object. Here I simply handle the null User case elegantly, which solved the originally reported User issue.

Handle weird edge case NPE where an import task has no user assigned
